export type Problem = {
  id:number; problem_id:string; source_type:"whitebook"|"past_exam"; category:"S"|"A"|"past_exam";
  chapter:number|null; problem_number:number; title:string; theme:string; priority:string; role:string;
  recommended_mode:string; linked_past_exams:string; linked_s_problems:string; linked_a_problems:string;
  notes:string; completion_status:string;
  strategy_rank?:"SS"|"S"|"A+"|"A";
  display_label?:string; difficulty?:number|null; roadmap_label?:string; normalized_label?:string;
  related_s_problem_ids?:string[]; linked_past_exam_ids?:string[];
  official_answer?:string; official_answer_url?:string;
  canonical_title?:string; canonical_problem_type?:string; canonical_keywords?:string[];
  roadmap_rank?:string; source_book?:string; related_a_problem_ids?:string[];
  related_past_exam_ids?:string[]; answer_available?:boolean; master_version?:string;
  metadata_status?:"ok"|"review_needed"|"metadata_review_needed";
};
export type AnswerIndexEntry = {
  problem_id:string; answer_available:boolean; pdf_file_name?:string; page_start?:number|null;
  page_end?:number|null; open_page?:number|null; document_key?:string; section_label?:string; answer_excerpt?:string;
  canonical_keywords?:string[]; imported_at?:string; index_version?:string;
};
export type CorrectionLog = {
  id?:number; auto_corrected:boolean; correction_fields:string[]; raw_gpt_problem_id:string;
  corrected_problem_id:string; raw_gpt_theme:string; corrected_theme:string;
  correction_reason:string; consistency_score:number; corrected_at:string;
};
export type ProblemAlias = { alias:string; problem_id:string; label?:string; imported_at?:string; alias_version?:string };
export type MasterImportLog = {
  id?:number; imported_at:string; file_kind:"integrated"|"problem_master"|"answer_index"|"aliases";
  version:string; problem_count:number; answer_count:number; alias_count:number;
};
export type DataDiagnostic = {
  id:string; severity:"info"|"warning"|"critical"; problem_id?:string; record_type:string;
  message:string; suggested_problem_id?:string; repairable:boolean;
  current_value?:string; suggested_value?:string; reason?:string;
  review_id?:number; source_problem_id?:string; target_problem_id?:string;
  current_related_ids?:string[]; canonical_related_ids?:string[];
  recommended_action?:"repair"|"remove"|"add_to_master"|"hold"|"ignore";
  task_id?:string; canonical_problem_id?:string; master_theme?:string; saved_derived_text?:string;
  derived_provenance?:string; target_attempt_id?:number; source_attempt_id?:number;
  effective_mode?:string; sheet_type?:string; due_date?:string; review_after_days?:number|null;
};
export type ProblemRelation = {
  relationId:string; sourceProblemId:string; targetProblemId:string;
  relationType:"prerequisite"|"remediation"|"extension";
  sourceIssue?:string; targetFocus:string; reason:string;
  relationSource:"problem_master"|"user_confirmed"|"gpt_suggestion";
  status:"confirmed"|"verified"|"candidate"|"rejected";
  createdAt:string; updatedAt:string;
};
export type ReviewOrigin="direct_attempt"|"verified_linked_problem"|"integration_schedule"|"transfer_schedule"|"past_exam_attempt"|"historical_completed";
export type PastExamSessionKind="scan_only"|"scan_plus_one"|"selected_three_timed"|"retrospective_review";
export type PastExamStage="discrimination"|"calibration"|"simulation";
export type ScanSetSource="past_exam_year"|"mixed_a_problems"|"custom_set";
export type PastExamExposure="unknown"|"unseen"|"prompt_scanned"|"partially_attempted"|"fully_attempted"|"answer_exposed"|"simulated";
export type ScanQuestion = {
  problemId?:string;questionLabel:string;predictedType:string;firstStep:string;
  predictedScore:number|null;predictedMinutes:number|null;sinkRisk:"low"|"medium"|"high";
  selected:boolean;selectionReason:string;plannedOrder:number|null;
  actualScore?:number|null;actualMinutes?:number|null;typeJudgmentCorrect?:boolean|null;
  firstStepCorrect?:boolean|null;sank?:boolean|null;hintUsed?:boolean;referenceUsed?:boolean;completed?:boolean;
};
export type LearningPurpose="error_repair"|"integration_check"|"transfer_check"|"exam_performance";
export type LearningStage="acquisition"|"repair"|"integration"|"discrimination"|"transfer"|"performance"|"stable";
export type AssessmentTiming="same_session_correction"|"delayed_retrieval"|"independent_performance";
export type TargetKind="mathematical_patch"|"skeleton_expression_patch";
export type KPolicyValidity="valid"|"invalid_legacy_k"|"needs_review";
export type Attempt = {
  id:number; problem_id:string; date:string; mode:string; time_minutes:number; mark:string;
  score_label:string; error_type:string; error_point:string; next_action:string; memo:string;
  score_text?:string; score_numeric?:number|null; score_max?:number|null; result_summary?:string;
  improvement_guidance?:string; required_derivation?:string; corrected_answer?:string;
  target_issue_resolved?:boolean; minimum_pass_condition_met?:boolean;
  resolution_evidence?:string; answer_change_summary?:string; required_work_shown?:string[];
  exam_selection_rank?:string; error_types?:string[]; primary_error_type?:string;
  secondary_error_type?:string; ignored_parts?:string[]; auto_imported?:boolean;
  import_confidence?:number; grading_confidence?:number|null; rubric_version?:string;
  uncertain_points?:string[]; generated_from_review_id?:number; is_review_attempt?:boolean;
  evaluation_scope?:string; graded_parts?:string[]; assumed_correct_parts?:string[];
  unresolved_carryover?:string[];
  review_scope?:"targeted_patch"|"full_skeleton"|"main_calc_target"|"check_only"|"full_answer"|"scan5";
  targeted_parts?:string[]; k_evidence?:string[]; k_evidence_valid?:boolean;
  effective_error_types?:string[];
  hint_used?:boolean; hint_level?:string; after_hint_reproduced?:boolean;
  reference_level?:number; no_hint?:boolean; one_line_hint?:boolean; previous_mistake?:boolean;
  official_answer?:boolean; gpt_explanation?:boolean;
  allowed_reference_level?:number; actual_reference_level?:number;
  reference_closed_reproduction?:boolean; saved_gpt_feedback?:boolean; external_reference?:boolean;
  task_origin?:"first_attempt"|"review_attempt"|"linked_s_check"|"related_drill"|"past_exam_followup";
  source_problem_id?:string; attempt_exists?:boolean;
  raw_problem_id?:string; id_corrected?:boolean; id_correction_reason?:string;
  raw_gpt_problem_id?:string; raw_gpt_theme?:string; auto_corrected?:boolean;
  correction_fields?:string[]; correction_reason?:string; consistency_score?:number;
  learning_purpose?:LearningPurpose; learning_stage?:LearningStage; assessment_timing?:AssessmentTiming;
  task_score?:number|null; exam_score?:number|null; exam_score_eligible?:boolean;
  time_limit_minutes?:number; conclusion_reached?:boolean; incomplete_reason?:string;
  retention_eligible?:boolean; problem_type_key?:string; transfer_evidence?:boolean;
  policy_validity?:KPolicyValidity; exclude_from_planning?:boolean;
  exclude_from_recurrence_metrics?:boolean; superseded_by_policy_version?:string;
  parent_past_session_id?:number;
};
export type Review = {
  id:number; problem_id:string; due_date:string; review_type:string; status:string; generated_from_attempt_id:number;
  duration_minutes?:number; reason?:string;
  review_reason?:string; review_method?:string; review_instruction?:string; review_steps?:string[];
  estimated_minutes?:number; requires_full_answer?:boolean; requires_s_check?:boolean;
  linked_s_problem_ids?:string[]; interval_days?:number; generated_from_past_session_id?:number;
  completion_result?:"success"|"partial"|"failed"; hint_used?:boolean; hint_level?:string; after_hint_reproduced?:boolean;
  reference_level?:number; no_hint?:boolean; one_line_hint?:boolean; previous_mistake?:boolean;
  official_answer?:boolean; gpt_explanation?:boolean;
  allowed_reference_level?:number; actual_reference_level?:number;
  reference_closed_reproduction?:boolean; saved_gpt_feedback?:boolean; external_reference?:boolean;
  completion_time_minutes?:number; completed_at?:string;
  manual_order?:number; postponed_count?:number; postpone_count?:number; last_postponed_at?:string;
  postponed_at?:string; postponed_to?:string; postpone_reason?:string; triage_override?:"must";
  task_origin?:"first_attempt"|"review_attempt"|"linked_s_check"|"related_drill"|"past_exam_followup";
  source_problem_id?:string; attempt_exists?:boolean; review_goal_public?:string; source_error_summary?:string;
  raw_problem_id?:string; id_corrected?:boolean; id_correction_reason?:string;
  inferred_mode?:"check"|"skeleton"|"main_calc"|"full"|"scan5";
  mode_override?:"check"|"skeleton"|"main_calc"|"full"|"scan5";
  effective_mode?:"check"|"skeleton"|"main_calc"|"full"|"scan5";
  sheet_type?:"check_sheet"|"skeleton_sheet"|"main_calc_sheet"|"full_answer_sheet"|"scan5_sheet";
  sheet_name?:string; derived_from_problem_id?:string; derived_from_attempt_id?:number;
  derived_from_master_version?:string; derived_generated_at?:string; derived_stale?:boolean;
  derived_fields?:Record<string,{value:unknown;provenance:{problemId:string;attemptId?:number;evaluationId?:number;relationId?:string;masterVersion:string;generatedAt:string}}>;
  raw_due_date?:string; due_date_correction_reason?:string; review_needed_reason?:string;
  review_scope?:"targeted_patch"|"full_skeleton"|"main_calc_target"|"check_only"|"full_answer"|"scan5";
  effective_review_scope?:"targeted_patch"|"full_skeleton"|"main_calc_target"|"check_only"|"full_answer"|"scan5";
  targeted_parts?:string[]; scope_completion_conditions?:string[];
  learning_purpose?:LearningPurpose; learning_stage?:LearningStage; assessment_timing?:AssessmentTiming;
  target_kind?:TargetKind; required_evidence?:string[];
  policy_version?:string; source_attempt_id?:number; deduplication_key?:string;
  earliest_date?:string; preferred_date?:string; latest_date?:string;
  retention_eligible?:boolean; success_transition?:string; failure_transition?:string;
  policy_validity?:KPolicyValidity; exclude_from_planning?:boolean;
  exclude_from_recurrence_metrics?:boolean; superseded_by_policy_version?:string;
  superseded_reason?:string;
  origin?:ReviewOrigin;origin_verified?:boolean;target_problem_id?:string;relation_id?:string;generated_at?:string;parent_past_session_id?:number;
};
export type TodayPlanSnapshot = {
  date:string;task_ids:string[];start_of_day_planned_minutes:number;
  initial_bucket:Record<string,"must"|"if_time"|"tomorrow">;
  initial_estimated_minutes:Record<string,number>;tasks:Task[];created_at:string;
};
export type WeakNote = {
  id:number; date:string; problem_id:string; error_type:string; theme:string; mistake:string;
  correction_rule:string; is_resolved:number; source_text?:string; auto_generated?:boolean;
  last_quizzed_at?:string; quiz_correct_count?:number; quiz_wrong_count?:number;
  generated_from_attempt_id?:number;
};
export type Roadmap = {
  id:number; order_index:number; problem_id:string; block_name:string; expected_mode:string; load_score:number; is_active:number;
};
export type PastSession = Record<string, unknown> & {
  id:number;year:number;session_type:string;date:string;session_kind?:PastExamSessionKind;stage?:PastExamStage;
  scan_set_source?:ScanSetSource;source_label?:string;questions?:ScanQuestion[];scan_minutes?:number;
  initial_selected_problem_ids?:string[];final_selected_problem_ids?:string[];solve_order?:string[];
  planned_minutes_by_problem?:Record<string,number>;selection_strategy?:string;actual_total_minutes?:number;
  changed_selection?:boolean;selection_change_reason?:string;answer_exposure?:boolean;review_minutes?:number;notes?:string;
  selection_evaluation_eligible?:boolean;optimal_selected_problem_ids?:string[];optimal_selection_basis?:string;
  exam_score_eligible?:boolean;prompt_scanned_at?:string;attempt_started_at?:string;attempt_completed_at?:string;
  answer_viewed_at?:string;simulation_completed_at?:string;linked_attempt_ids?:number[];
  analysis?:Record<string,unknown>;rubric_version?:string;
};
export type Task = {
  id?:number; problem_id:string; title:string; kind:string; reason:string; mode:string;
  minutes:number; load:number; status?:string; error_type?:string; theme?:string;
  due_date?:string; review_type?:string; review_reason?:string; review_method?:string; review_instruction?:string;
  review_steps?:string[]; estimated_minutes?:number; requires_full_answer?:boolean;
  requires_s_check?:boolean; linked_s_problem_ids?:string[]; checked?:boolean;
  previous_date?:string; previous_score?:string; previous_errors?:string[];
  previous_error_point?:string; previous_next_action?:string;
  previous_improvement_guidance?:string; previous_required_derivation?:string;
  previous_corrected_answer?:string; triage?:"must"|"if_time"|"tomorrow";
  official_answer_text?:string; official_answer_url?:string; has_saved_gpt_feedback?:boolean;
  official_answer_pdf_name?:string; official_answer_pdf_registered?:boolean; answer_section_label?:string;
  official_answer_page?:number|null; answer_page_start?:number|null; answer_page_end?:number|null; answer_document_key?:string;
  canonical_problem_type?:string; canonical_keywords?:string[]; answer_excerpt?:string;
  allowed_reference_level?:number; actual_reference_level?:number;
  reference_closed_reproduction?:boolean; triage_override?:"must";
  postponed_at?:string; postponed_to?:string; postpone_reason?:string; postpone_count?:number;
  task_origin?:"first_attempt"|"review_attempt"|"linked_s_check"|"related_drill"|"past_exam_followup";
  source_problem_id?:string; attempt_exists?:boolean; review_goal_public?:string; source_error_summary?:string;
  inferred_mode?:"check"|"skeleton"|"main_calc"|"full"|"scan5";
  mode_override?:"check"|"skeleton"|"main_calc"|"full"|"scan5";
  effective_mode?:"check"|"skeleton"|"main_calc"|"full"|"scan5";
  sheet_type?:"check_sheet"|"skeleton_sheet"|"main_calc_sheet"|"full_answer_sheet"|"scan5_sheet";
  consistency_warnings?:Array<{code:string;message:string;repairable:boolean;blocksSpecificGuidance?:boolean}>;
  review_needed?:boolean;
  review_scope?:"targeted_patch"|"full_skeleton"|"main_calc_target"|"check_only"|"full_answer"|"scan5";
  effective_review_scope?:"targeted_patch"|"full_skeleton"|"main_calc_target"|"check_only"|"full_answer"|"scan5";
  targeted_parts?:string[]; scope_completion_conditions?:string[];
  learning_purpose?:LearningPurpose; learning_stage?:LearningStage; assessment_timing?:AssessmentTiming;
  target_kind?:TargetKind; required_evidence?:string[];
  policy_version?:string; source_attempt_id?:number; deduplication_key?:string;
  earliest_date?:string; preferred_date?:string; latest_date?:string;
  retention_eligible?:boolean;success_transition?:string;failure_transition?:string;
};
export type WeaknessInsight = {
  theme:string; score:number; level:"重点"|"注意"|"観察"; confidence:"参考"|"暫定"|"分析可能";
  sampleCount:number; latestDate:string; dominantError:string; recurrence:number;
  errorCounts:Record<string,number>; evidence:string[]; recommendedA:string[]; recommendedS:string[];
  action:string; mode:string; minutes:number; load:number;
};
export type Dashboard = {
  today:string; weekA:number; weekPast:number; kRecurrence:number; pending:number; overdue:number;
  sStableRate:number; sForgotten:number; scanSuccess:number; examSuccess:number;
  dangerChapters:{chapter:number;count:number}[]; nextTheme:string;
  analysisConfidence:"参考"|"暫定"|"分析可能"; analysisAttemptCount:number;
  weaknessInsights:WeaknessInsight[];
  readiness:{
    unseenScoreRate:number|null;timedCompletionRate:number|null;selectionSuccessRate:number|null;
    pastExamScoreRate:number|null;kRecurrenceRate:number|null;repeatedWRate:number|null;
    typeIdentificationAccuracy:number|null;firstStepAccuracy:number|null;
    predictedScoreCalibration:number|null;predictedTimeCalibration:number|null;
    sampleSizes:{unseen:number;timed:number;scans:number;pastExams:number;kReviews:number;wReviews:number};
  };
  stableRelease:{isStable:boolean;blockingIssues:string[];message:string};
  weeklyQuota:{fullSkeleton:number;timedFull:number;scan5:number;
    deficits:{fullSkeleton:boolean;timedFull:boolean;scan5:boolean};
    candidates:Array<{kind:"full_skeleton"|"timed_full"|"scan5";minutes:number;sessionKind?:PastExamSessionKind;stage?:PastExamStage}>};
  pace:{label:string;checks:boolean[];items:{label:string;detail:string;status:"ok"|"warning"|"pending"}[];
    a14:number;pastSkeleton:number;kRepeat:number;skeletonRate:number;weakUpdates:number;delayed3:number;
    suggestion:string;dangerCriteria:string[];phase:string;phaseLabel:string;summary:string;allocation:string;nextPhase:string;daysRemaining:number;examDateIsEstimate:boolean};
};
export type Bootstrap = {
  problems:Problem[]; attempts:Attempt[]; reviews:Review[]; roadmap:Roadmap[];
  weakNotes:WeakNote[]; pastSessions:PastSession[]; answerIndex:AnswerIndexEntry[]; problemAliases:ProblemAlias[]; dashboard:Dashboard;
  settings:{exam_date:string;daily_study_minutes:number};
  masterStatus:{problem_count:number;answer_count:number;problem_version:string;answer_version:string;
    problem_updated_at:string;answer_updated_at:string;alias_updated_at:string;alias_version:string;alias_count:number;
    pdf_files:string[];pdf_documents:{document_key:string;kind?:string;source_book?:string;original_file_name?:string;
      display_name?:string;page_count?:number;sha256?:string;registered_at?:string;file_name?:string;answer_count:number}[];
    diagnostics:DataDiagnostic[];import_history:string[];
    review_rebuild_summary?:{repaired_at:string;stale_count:number;regenerated_count:number;review_needed_count:number;source_target_mix_count:number;date_corrected_count:number};
    legacy_k_summary?:{analyzed_at:string;invalid_legacy_k_count:number;needs_review_count:number;
      superseded_task_count:number;resolved_task_count:number;policy_version:string;preview?:boolean};
    source_mismatch_summary?:{reorganized_at:string;source_mismatch_count:number;verified_relation_count:number;
      superseded_count:number;regenerated_count:number;needs_review_count:number;unchanged_completed_count:number;
      active_source_mismatch?:number;pending_verified_link_needs_migration?:number;
      invalid_legacy_cards_to_supersede?:number;historical_completed_linked_reviews?:number;
      unresolved_needs_review?:number;verified_relation_migrated?:number;
      policy_version:string;preview?:boolean};
  };
  databaseStatus:{
    databaseName:string;databaseVersion:number;requiredDatabaseVersion:number;requestedStores:string[];
    existingStores:string[];missingStores:string[];extraStores:string[];operation:string;appSchemaVersion:string;
    buildVersion:string;migrationVersion:string;valid:boolean;lastMigration:string;migrationResult:string;migratedAt:string;
    counts:{attempts:number;evaluations:number;reviewPlans:number};
  };
  today:{tasks:Task[];totalLoad:number;plannedMinutes:number;remainingMinutes:number;actualMinutes:number;
    targetMinutes:number;capacityPercent:number;warning:string;guidance:string;
    triageMinutes?:{must:number;if_time:number;tomorrow:number};
    planned_minutes_total:number;completed_minutes_today:number;remaining_minutes_today:number;
    postponed_minutes_today:number;target_minutes_today:number;
    start_of_day_planned_minutes:number;active_remaining_minutes:number;
    postpone_candidate_minutes:number;active_total_if_done:number;
    triageCounts:{must:number;if_time:number;tomorrow:number;completed:number};
    completedTasks:Task[]};
};
export type StudyUpdate = {
  problem_id:string; date:string; mode:string; time_minutes?:number|string; actual_minutes?:number|string;
  estimated_minutes?:number|string; mark:string; score_label:string;
  error_type:string; error_point:string; next_action:string; review_after_days?:number|string;
  linked_s_problem?:string; linked_past_exam?:string; theme?:string; correction_rule?:string;
  display_label?:string; source_type?:"whitebook"|"past_exam"; category?:"S"|"A"|"past_exam";
  chapter?:number|null; problem_number?:number; difficulty?:number|null; themes?:string[];
  related_s_problem_ids?:string[]; linked_s_problems?:string[]; linked_past_exams?:string[];
  parent_past_session_id?:number|string;
  ignored_parts?:string[]; score_text?:string; score_numeric?:number|null; score_max?:number|null;
  result_summary?:string; exam_selection_rank?:string; error_types?:string[];
  improvement_guidance?:string; required_derivation?:string; corrected_answer?:string;
  target_issue_resolved?:boolean; minimum_pass_condition_met?:boolean;
  resolution_evidence?:string; answer_change_summary?:string; required_work_shown?:string[];
  primary_error_type?:string; secondary_error_type?:string; review_reason?:string; review_method?:string;
  weak_note?:{theme:string;error_type:string;mistake:string;correction_rule:string};
  weak_notes?:Array<{theme:string;error_type:string;mistake:string;correction_rule:string}>;
  s_check_suggestions?:Array<{problem_id?:string;reason?:string}>;
  date_expression_warnings?:string[]; date_expressions_removed?:boolean;
  source_text?:string; auto_imported?:boolean; import_confidence?:number;
  grading_confidence?:number|null; rubric_version?:string; uncertain_points?:string[];
  generated_from_review_id?:number; review_outcome?:"success"|"partial"|"failed"; hint_used?:boolean;
  task_origin?:"first_attempt"|"review_attempt"|"linked_s_check"|"related_drill"|"past_exam_followup";
  hint_level?:string; after_hint_reproduced?:boolean; after_reference_reproduced?:boolean;
  reference_level?:number; no_hint?:boolean; one_line_hint?:boolean; previous_mistake?:boolean;
  official_answer?:boolean; gpt_explanation?:boolean;
  allowed_reference_level?:number; actual_reference_level?:number;
  reference_closed_reproduction?:boolean; saved_gpt_feedback?:boolean; external_reference?:boolean;
  evaluation_scope?:string; graded_parts?:string[]; assumed_correct_parts?:string[];
  unresolved_carryover?:string[];
  review_scope?:"targeted_patch"|"full_skeleton"|"main_calc_target"|"check_only"|"full_answer";
  targeted_parts?:string[]; completion_conditions?:string[];
  k_evidence?:string[]; k_evidence_valid?:boolean; effective_error_types?:string[];
  master_matched?:boolean; status?:string; math_localized?:boolean;
  main_theme?:string; raw_gpt_problem_id?:string; raw_gpt_theme?:string;
  auto_corrected?:boolean; correction_fields?:string[]; corrected_problem_id?:string;
  corrected_theme?:string; correction_reason?:string; consistency_score?:number;
  suggested_problem_id?:string; suggested_problem_label?:string; requires_problem_confirmation?:boolean;
  problem_id_confirmed?:boolean; problem_id_source?:"yaml"|"manual"|"alias"|"text";
  ignored_problem_candidates?:Array<{problem_id:string;reason:string}>;
  answer_excerpt?:string; canonical_keywords?:string[]; canonical_problem_type?:string;
  learning_purpose?:LearningPurpose; learning_stage?:LearningStage; assessment_timing?:AssessmentTiming;
  target_kind?:TargetKind; task_score?:number|null; exam_score?:number|null; exam_score_eligible?:boolean;
  time_limit_minutes?:number; conclusion_reached?:boolean; incomplete_reason?:string;
  raw_import_data?:Record<string,unknown>; raw_time_minutes?:number|string; raw_score_label?:string;
  raw_reference_closed_reproduction?:boolean;
};
